// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/GlebMoskalev/go-pickup-point-api/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// Product is an autogenerated mock type for the Product type
type Product struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, receptionID, productType
func (_m *Product) Create(ctx context.Context, receptionID string, productType string) (*entity.Product, error) {
	ret := _m.Called(ctx, receptionID, productType)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*entity.Product, error)); ok {
		return rf(ctx, receptionID, productType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *entity.Product); ok {
		r0 = rf(ctx, receptionID, productType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, receptionID, productType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteLastProduct provides a mock function with given fields: ctx, receptionID
func (_m *Product) DeleteLastProduct(ctx context.Context, receptionID string) error {
	ret := _m.Called(ctx, receptionID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLastProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, receptionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewProduct creates a new instance of Product. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProduct(t interface {
	mock.TestingT
	Cleanup(func())
}) *Product {
	mock := &Product{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
